project_id = "mcdidffxwtnqhawqilln"

[functions.asaas-import-customers]
verify_jwt = true

[functions.process-client-registration]
verify_jwt = false

[functions.notify-registration-admin]
verify_jwt = false

[functions.update-payment-urls]
verify_jwt = false

[functions.process-checkout]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.process-scheduled-reminders]
verify_jwt = false

[functions.billing-notifications]
verify_jwt = false

[functions.billing-diagnostics]
verify_jwt = false

[functions.inter-webhook]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.payment-confirmed-notification]
verify_jwt = false

[functions.generate-next-charge]
verify_jwt = false

[functions.assinafy-webhook]
verify_jwt = false
